// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Omotemachi.Infrastructure.Persistance.AppContext;

#nullable disable

namespace Omotemachi.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CardPack", b =>
                {
                    b.Property<int>("CardsId")
                        .HasColumnType("integer");

                    b.Property<int>("PacksId")
                        .HasColumnType("integer");

                    b.HasKey("CardsId", "PacksId");

                    b.HasIndex("PacksId");

                    b.ToTable("CardPacks", (string)null);
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Guild", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Config.ChannelsConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long?>("GeneralChannelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ImageSaverChannelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("NitroBoostingChannelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OfftopChannelId")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId");

                    b.ToTable("ChannelsConfig");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Config.EconomyConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("DailyBonus")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultCurrencyIcon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DonateCurrencyIcon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GuildId");

                    b.ToTable("EconomyConfigs");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Config.ExperienceConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int?>("ExpForMessage")
                        .HasColumnType("integer");

                    b.Property<int?>("ExpForVoiceMinute")
                        .HasColumnType("integer");

                    b.HasKey("GuildId");

                    b.ToTable("ExperienceConfig");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Config.LogsConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("CommandInteractionsWebhookUrl")
                        .HasColumnType("text");

                    b.Property<string>("ElseWebhookUrl")
                        .HasColumnType("text");

                    b.Property<string>("GuildWebhookUrl")
                        .HasColumnType("text");

                    b.Property<string>("MembersWebhookUrl")
                        .HasColumnType("text");

                    b.Property<string>("MessagesWebhookUrl")
                        .HasColumnType("text");

                    b.Property<string>("TicketsWebhookUrl")
                        .HasColumnType("text");

                    b.Property<string>("VoiceWebhookUrl")
                        .HasColumnType("text");

                    b.HasKey("GuildId");

                    b.ToTable("LogsConfig");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Config.LootboxesConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("ActiveLootboxes")
                        .HasColumnType("text");

                    b.Property<int?>("BackgroundsLootboxKeyPrice")
                        .HasColumnType("integer");

                    b.Property<int?>("RolesLootboxKeyPrice")
                        .HasColumnType("integer");

                    b.HasKey("GuildId");

                    b.ToTable("LootboxesConfigs");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Config.PacksConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("PacksPrice")
                        .HasColumnType("integer");

                    b.HasKey("GuildId");

                    b.ToTable("PacksConfigs");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Config.QuestsConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long?>("QuestsChannelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("QuestsMessageId")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId");

                    b.ToTable("QuestsConfigs");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Config.RolesConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeveloperRoleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ModeratorRoleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SupportRoleId")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId");

                    b.ToTable("RolesConfig");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Config.ShopConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ShopChannelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ShopMessageId")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId");

                    b.ToTable("ShopConfig");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Config.TicketsConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TicketChannelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TicketMessageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TicketReportChannelId")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId");

                    b.ToTable("TicketsConfig");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Config.VoiceConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CustomVoiceCategoryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CustomVoiceCreationChannelId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CustomVoiceDeletionTime")
                        .HasColumnType("integer");

                    b.HasKey("GuildId");

                    b.ToTable("VoiceConfig");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Duet", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProposerId")
                        .HasColumnType("bigint");

                    b.Property<long>("DuoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<long>("TogetherFrom")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId", "ProposerId", "DuoId");

                    b.HasIndex("DuoId");

                    b.HasIndex("ProposerId");

                    b.ToTable("Duets");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Interactions.InteractionsAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("AssetUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("InteractionsAssets");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InventoryId"));

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("InventoryId");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.InventoryItems.InventoryExpBooster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpBoosterId")
                        .HasColumnType("integer");

                    b.Property<int>("InventoryId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpBoosterId");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryExpBoosters");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.InventoryItems.InventoryLootboxKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryId")
                        .HasColumnType("integer");

                    b.Property<int>("LootboxKeyId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("LootboxKeyId");

                    b.ToTable("InventoryLootboxKeys");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.InventoryItems.InventoryRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("RoleId");

                    b.ToTable("InventoryRoles");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Items.ActiveExpBooster", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ActivatedAt")
                        .HasColumnType("bigint");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ActiveExpBoosters");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Items.ExpBooster", b =>
                {
                    b.Property<int>("ExpBoosterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExpBoosterId"));

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ExpBoosterId");

                    b.HasIndex("GuildId");

                    b.ToTable("ExpBoosters");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Items.LootboxKey", b =>
                {
                    b.Property<int>("LootboxKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LootboxKeyId"));

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("LootboxKeyId");

                    b.HasIndex("GuildId");

                    b.ToTable("LootboxKeys");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Items.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildRoleId")
                        .HasColumnType("bigint");

                    b.HasKey("RoleId");

                    b.HasIndex("GuildId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Lootboxes.LootboxRole", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildRoleId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Exclusive")
                        .HasColumnType("boolean");

                    b.Property<int>("LootboxType")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "GuildRoleId");

                    b.ToTable("LootboxRoles");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Lootboxes.LootboxUserData", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("LootboxType")
                        .HasColumnType("integer");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GuildId", "UserId", "LootboxType");

                    b.HasIndex("UserId");

                    b.ToTable("LootboxUserDatas");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Quests.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long?>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CompletableUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAvailableNow")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<int>("Required")
                        .HasColumnType("integer");

                    b.Property<int>("RewardAmount")
                        .HasColumnType("integer");

                    b.Property<int>("RewardType")
                        .HasColumnType("integer");

                    b.Property<int>("TaskType")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Quests.UserQuest", b =>
                {
                    b.Property<int>("QuestId")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.HasKey("QuestId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserQuests");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Settings.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Settings.UserSetting", b =>
                {
                    b.Property<int>("SettingId")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("State")
                        .HasColumnType("boolean");

                    b.HasKey("SettingId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Shop.ShopKey", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("LootboxType")
                        .HasColumnType("integer");

                    b.Property<bool>("Exclusive")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId", "LootboxType");

                    b.ToTable("ShopKeys");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Shop.ShopRole", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildRoleId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Exclusive")
                        .HasColumnType("boolean");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "GuildRoleId");

                    b.ToTable("ShopRoles");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Shop.ShopRoleTries", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildRoleId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("TriesUsed")
                        .HasColumnType("integer");

                    b.Property<long?>("TryActivated")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId", "UserId", "GuildRoleId");

                    b.HasIndex("UserId");

                    b.ToTable("ShopRolesTries");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Ticket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateClose")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescriptionProblem")
                        .HasColumnType("text");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ModeratorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Solution")
                        .HasColumnType("text");

                    b.Property<string>("TypeProblem")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("PayerId")
                        .HasColumnType("bigint");

                    b.Property<long>("RecipientId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("PayerId");

                    b.HasIndex("RecipientId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Logs.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("FilesUrls")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<string[]>("ImagesUrls")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Member", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("Coins")
                        .HasColumnType("integer");

                    b.Property<int>("Crystals")
                        .HasColumnType("integer");

                    b.Property<int>("ExpMultiplier")
                        .HasColumnType("integer");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GuildId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Statistics.CardsStatistics", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("CardsGiftedCount")
                        .HasColumnType("integer");

                    b.Property<int>("CardsSwappedToPackCount")
                        .HasColumnType("integer");

                    b.Property<int>("CardsTradedCount")
                        .HasColumnType("integer");

                    b.Property<int>("PacksOpenedCount")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "GuildId");

                    b.HasIndex("GuildId");

                    b.ToTable("CardStatistics");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Statistics.DNDStatistics", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("DNDDiceRolledCount")
                        .HasColumnType("integer");

                    b.Property<int>("DNDDiceRolledMaxCount")
                        .HasColumnType("integer");

                    b.Property<int>("DNDDiceRolledMinCount")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "GuildId");

                    b.HasIndex("GuildId");

                    b.ToTable("DNDStatistics");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Statistics.DuetsStatistics", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("DuetsCreatedCount")
                        .HasColumnType("integer");

                    b.Property<int>("DuetsDivorcedCount")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "GuildId");

                    b.HasIndex("GuildId");

                    b.ToTable("DuetsStatistics");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Statistics.InventoryStatistics", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("ExpBoostersActivatedCount")
                        .HasColumnType("integer");

                    b.Property<int>("ExpGainedWithBoosters")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "GuildId");

                    b.HasIndex("GuildId");

                    b.ToTable("InventoryStatistics");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Statistics.LootboxesStatistics", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("BackgroundsLootboxesOpenedCount")
                        .HasColumnType("integer");

                    b.Property<int>("LootboxesBackgroundsDroppedCount")
                        .HasColumnType("integer");

                    b.Property<int>("LootboxesRolesDroppedCount")
                        .HasColumnType("integer");

                    b.Property<int>("RolesLootboxesOpenedCount")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "GuildId");

                    b.HasIndex("GuildId");

                    b.ToTable("LootboxesStatistics");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Statistics.MembersStatistics", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("CoinsAmountChangedCount")
                        .HasColumnType("integer");

                    b.Property<int>("CrystalsAmountChangedCount")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "GuildId");

                    b.HasIndex("GuildId");

                    b.ToTable("MembersStatistics");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Statistics.MessagesStatistics", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("MessagesWritenCount")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "GuildId");

                    b.HasIndex("GuildId");

                    b.ToTable("MessagesStatistics");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Statistics.QuestsStatistics", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("CardsPacksFromQuestsCount")
                        .HasColumnType("integer");

                    b.Property<int>("CoinsFromQuestsCount")
                        .HasColumnType("integer");

                    b.Property<int>("CrystallsFromQuestsCount")
                        .HasColumnType("integer");

                    b.Property<int>("LootboxKeysFromQuestsCount")
                        .HasColumnType("integer");

                    b.Property<int>("QuestsAssignedCount")
                        .HasColumnType("integer");

                    b.Property<int>("QuestsCompletedCount")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "GuildId");

                    b.HasIndex("GuildId");

                    b.ToTable("QuestsStatistics");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Statistics.TicketsStatistics", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("DeveloperTicketCreatedCount")
                        .HasColumnType("integer");

                    b.Property<int>("ModeratorTicketCreatedCount")
                        .HasColumnType("integer");

                    b.Property<int>("SupportTicketCreatedCount")
                        .HasColumnType("integer");

                    b.Property<int>("TicketsWasClosedCount")
                        .HasColumnType("integer");

                    b.Property<int>("TicketsWasStartedCount")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "GuildId");

                    b.HasIndex("GuildId");

                    b.ToTable("TicketsStatistics");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Statistics.VoiceStatistics", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("VoiceTimeMuted")
                        .HasColumnType("integer");

                    b.Property<int>("VoiceTimeUnMuted")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "GuildId");

                    b.HasIndex("GuildId");

                    b.ToTable("VoiceStatistics");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Wacky.Appa.Appa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Appas");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Wacky.Appa.TimeoutAppaCatch", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastCatch")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GuildId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TimeoutAppaCatches");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Wacky.Appa.UserAppa", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("AppaId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "UserId", "AppaId");

                    b.HasIndex("AppaId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAppas");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Wacky.CCG.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<List<string>>("AssetsUrls")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Wacky.CCG.Pack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSeriesSpecific")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("Packs");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Wacky.CCG.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<List<string>>("Aliases")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Wacky.CCG.TimeoutCardCatch", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastGive")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GuildId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TimeoutCardCatches");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Wacky.CCG.UserCard", b =>
                {
                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("AssetIndex")
                        .HasColumnType("integer");

                    b.HasKey("CardId", "UserId", "GuildId");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCards");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Wacky.CCG.UserPack", b =>
                {
                    b.Property<int>("PackId")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.HasKey("PackId", "UserId", "GuildId");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPacks");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CardPack", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Wacky.CCG.Card", null)
                        .WithMany()
                        .HasForeignKey("CardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.Domain.Wacky.CCG.Pack", null)
                        .WithMany()
                        .HasForeignKey("PacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Config.ChannelsConfig", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Config.EconomyConfig", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Config.ExperienceConfig", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Config.LogsConfig", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Config.LootboxesConfig", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Config.PacksConfig", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Config.QuestsConfig", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Config.RolesConfig", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Config.ShopConfig", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Config.TicketsConfig", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Config.VoiceConfig", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Duet", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.User", "Duo")
                        .WithMany()
                        .HasForeignKey("DuoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "Proposer")
                        .WithMany()
                        .HasForeignKey("ProposerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Duo");

                    b.Navigation("Guild");

                    b.Navigation("Proposer");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Inventory", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.InventoryItems.InventoryExpBooster", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Jester.Items.ExpBooster", "ExpBooster")
                        .WithMany()
                        .HasForeignKey("ExpBoosterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.Domain.Jester.Inventory", "Inventory")
                        .WithMany("InventoryExpBoosters")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpBooster");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.InventoryItems.InventoryLootboxKey", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Jester.Inventory", "Inventory")
                        .WithMany("InventoryLootboxKeys")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.Domain.Jester.Items.LootboxKey", "LootboxKey")
                        .WithMany()
                        .HasForeignKey("LootboxKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("LootboxKey");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.InventoryItems.InventoryRole", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Jester.Inventory", "Inventory")
                        .WithMany("InventoryRoles")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.Domain.Jester.Items.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Items.ActiveExpBooster", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Items.ExpBooster", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Items.LootboxKey", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Items.Role", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Lootboxes.LootboxRole", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Lootboxes.LootboxUserData", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Quests.Quest", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Quests.UserQuest", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Jester.Quests.Quest", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Settings.Setting", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Settings.UserSetting", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Jester.Settings.Setting", "Setting")
                        .WithMany()
                        .HasForeignKey("SettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Shop.ShopKey", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Shop.ShopRole", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Shop.ShopRoleTries", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Ticket", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Transaction", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "Payer")
                        .WithMany()
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("Payer");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Logs.LogEntry", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Member", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Statistics.CardsStatistics", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Statistics.DNDStatistics", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Statistics.DuetsStatistics", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Statistics.InventoryStatistics", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Statistics.LootboxesStatistics", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Statistics.MembersStatistics", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Statistics.MessagesStatistics", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Statistics.QuestsStatistics", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Statistics.TicketsStatistics", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Statistics.VoiceStatistics", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Wacky.Appa.TimeoutAppaCatch", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Wacky.Appa.UserAppa", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Wacky.Appa.Appa", "Appa")
                        .WithMany()
                        .HasForeignKey("AppaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appa");

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Wacky.CCG.Card", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Wacky.CCG.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Wacky.CCG.Pack", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Wacky.CCG.Series", "SpecificSeries")
                        .WithMany()
                        .HasForeignKey("SeriesId");

                    b.Navigation("SpecificSeries");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Wacky.CCG.TimeoutCardCatch", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Wacky.CCG.UserCard", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Wacky.CCG.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Wacky.CCG.UserPack", b =>
                {
                    b.HasOne("Omotemachi.Models.V1.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.Domain.Wacky.CCG.Pack", "Pack")
                        .WithMany()
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omotemachi.Models.V1.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("Pack");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omotemachi.Models.V1.Domain.Jester.Inventory", b =>
                {
                    b.Navigation("InventoryExpBoosters");

                    b.Navigation("InventoryLootboxKeys");

                    b.Navigation("InventoryRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
